basePath: /
definitions:
  domain.Book:
    properties:
      author:
        type: string
      category:
        items:
          $ref: '#/definitions/domain.Category'
        type: array
      id:
        type: string
      isActive:
        type: boolean
      isFavorite:
        type: boolean
      isbn:
        type: string
      language:
        items:
          $ref: '#/definitions/domain.Language'
        type: array
      pageCount:
        type: integer
      publishYear:
        type: integer
      publisher:
        type: string
      summary:
        type: string
      title:
        type: string
    required:
    - author
    - publishYear
    - publisher
    - title
    type: object
  domain.Category:
    properties:
      categoryType:
        items:
          $ref: '#/definitions/domain.CategoryType'
        type: array
      id:
        type: string
      isActive:
        type: boolean
      title:
        type: string
    required:
    - title
    type: object
  domain.CategoryType:
    properties:
      id:
        type: string
      isActive:
        type: boolean
      title:
        type: string
    required:
    - title
    type: object
  domain.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  domain.Language:
    properties:
      id:
        type: string
      isActive:
        type: boolean
      name:
        type: string
    required:
    - name
    type: object
  domain.SuccessResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: s.shargi.gh@gmail.com
    name: Saeed Sharghi Ghazani
    url: https://github.com/saeedshargi
  description: This is a simple application to manage personal interests
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  termsOfService: http://swagger.io/terms/
  title: Benim-Go
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /books:
    post:
      consumes:
      - application/json
      description: Create a new book with the input paylod
      parameters:
      - description: Create book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/domain.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Create a new book
      tags:
      - books
schemes:
- http
swagger: "2.0"
